name = "dht-testground"

[defaults]
builder = "docker:node"
runner = "local:docker"

[builders."docker:node"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "peer-routing"
instances = { min = 6, max = 100, default = 12 }
